- CHANGELOG.md
- src/stock-products/full-stock-card-summary-repository-impl.js
- src/stock-products/full-stock-card-summary-repository-impl.spec.js
https://openlmis.atlassian.net/browse/OLMIS-6328
It looks like it doesn't matter what is returned from the orderable fulfills - no matter what it returns, the later result will be the same.
> OLMIS-6328: Removed unnecessary call to /orderableFullfils

- CHANGELOG.md
- src/stock-physical-inventory-mobile/physical-inventory-form.component.jsx
TICKET: https://openlmis.atlassian.net/browse/OLMIS-7581
REVIEW: https://review.openlmis.org/cru/FEOLMIS-4596
> OLMIS-7581: modified way of sorting product in the form

- CHANGELOG.md
- src/stock-physical-inventory-mobile/physical-inventory-form.component.jsx
TICKET: https://openlmis.atlassian.net/browse/OLMIS-7588
REVIEW: https://review.openlmis.org/cru/FEOLMIS-4596
> OLMIS-7588: Physical Inventory validation for unaccounted quantity - mobile

- CHANGELOG.md
- src/stock-physical-inventory/physical-inventory.factory.js
TICKET: https://openlmis.atlassian.net/browse/OLMIS-7582
REVIEW: https://review.openlmis.org/cru/FEOLMIS-4597
> OLMIS-7582: fixed getStockAdjustment function when there is no draft

- src/stock-adjustment-mobile/_adjustment-mobile.scss
- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-adjustment-mobile/adjustment-app.jsx
- src/stock-adjustment-mobile/adjustment-form.component.jsx
- src/stock-adjustment-mobile/adjustment-mobile.html
- src/stock-adjustment-mobile/adjustment-mobile.module.js
- src/stock-adjustment-mobile/adjustment-mobile.routes.js
- src/stock-adjustment-mobile/adjustment-mobile.wrapper.jsx
- src/stock-adjustment-mobile/components/block-list.component.jsx
- src/stock-adjustment-mobile/components/read-only-table.component.jsx
- src/stock-adjustment-mobile/components/toast.component.jsx
- src/stock-adjustment-mobile/components/toast.css
- src/stock-adjustment-mobile/format-utils.jsx
- src/stock-adjustment-mobile/messages_en.json
- src/stock-adjustment-mobile/program-select.jsx
- src/stock-adjustment-mobile/reducers/adjustment.jsx
- src/stock-adjustment-mobile/reducers/facilities.jsx
- src/stock-adjustment-mobile/reducers/product-options.jsx
- src/stock-adjustment-mobile/reducers/program.jsx
- src/stock-adjustment-mobile/reducers/reasons.jsx
- src/stock-adjustment-mobile/reducers/toasts.jsx
- src/stock-adjustment-mobile/store.jsx
part of TICKET: https://openlmis.atlassian.net/browse/MW-1147
includes:
- a whole new 'program select' design as a table component instead of 'select input'
- Product Add Form to add position for Adjustment
- Toast to inform about Adjustment status after executing 'SubmitAdjustment' - success/error
- BlockList component to display AdjustmentSummary. It displays products that are going to be 'adjusted'.
- Possibility to add another adjustment position in Adjustment Summary
- Possibility to Submit Adjustment based on what is displayed on BlockList. Stocks are updated after this operation. 
- Delete Adjustment in Adjustment Summary Page
Additional info:
- Tost, BlockList and ReadOnlyTable component could be moved later into separate openLMIS module called 'ui-components'.
To-do in part 2:
- …
> MW-1147: Implementation of Adjustments tab - first part

- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-adjustment-mobile/adjustment-app.jsx
- src/stock-adjustment-mobile/adjustment-form.component.jsx
- src/stock-adjustment-mobile/adjustment-mobile.routes.js
- src/stock-adjustment-mobile/components/block-list.component.jsx
- src/stock-adjustment-mobile/edit-product-page/edit-product-page.jsx
- src/stock-adjustment-mobile/format-utils.jsx
- src/stock-adjustment-mobile/reducers/adjustment.jsx
TICKET part 2: https://openlmis.atlassian.net/browse/MW-1147
New features:
- 'onClick' function for 'BlockList' particular row
- added 'EditProductPage'
- added 'Delete' on 'EditProductPage'
- added 'Save' on 'EditProductPage'
- added cancel as 'X' icon on 'EditProductPage' (right top)
> MW-1147: added EditProductPage for Adjustment in mobile app

- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
TICKET: https://openlmis.atlassian.net/browse/MW-1147
Quick fix - detected on UAT. Web console shows error with 'cannot delete property' (because of having immutable object).
> MW-1147: hotfix for 'AddProductPage' decorator - delete lot - immutable object

- src/stock-adjustment-mobile/_adjustment-mobile.scss
- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-adjustment-mobile/adjustment-app.jsx
- src/stock-adjustment-mobile/adjustment-form.component.jsx
- src/stock-adjustment-mobile/components/date-input.component.jsx
- src/stock-adjustment-mobile/edit-product-page/edit-product-page.jsx
- src/stock-adjustment-mobile/format-utils.jsx
- src/stock-adjustment-mobile/program-select.jsx
TICKET: https://openlmis.atlassian.net/browse/MW-1168
Changes: 
- improvements in UI for example bigger buttons (in NavBar), full width inputs/fields in forms, add indications that particular field is obligatory in form. 
- editable lot code (EditProductPage)\
- Toast for 'offline' mode and mechanism to show it while running offline mode. 
- Menu is not displayed on 'AddProductPage/EditProductPage'
- number input text aligned to right
- DateInput component
> MW-1168: additional changes in UI and mechanism in Adjustment

- CHANGELOG.md
- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-adjustment-mobile/adjustment-form.component.jsx
- src/stock-adjustment-mobile/edit-product-page/edit-product-page.jsx
- src/stock-adjustment-mobile/store.jsx
TICKET: https://openlmis.atlassian.net/browse/OLMIS-7599
part of https://openlmis.atlassian.net/browse/MW-1147 and https://openlmis.atlassian.net/browse/MW-1168
> OLMIS-7599: fixing refreshing and reloading app

- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-adjustment-mobile/adjustment-app.jsx
- src/stock-adjustment-mobile/adjustment-form.component.jsx
- src/stock-adjustment-mobile/adjustment-mobile.wrapper.jsx
- src/stock-adjustment-mobile/components/block-list.component.jsx
- src/stock-adjustment-mobile/components/toast.component.jsx
- src/stock-adjustment-mobile/edit-product-page/edit-product-page.jsx
- src/stock-adjustment-mobile/program-select.jsx
- src/stock-adjustment-mobile/reducers/adjustment.jsx
- src/stock-adjustment-mobile/reducers/facilities.jsx
- src/stock-adjustment-mobile/reducers/product-options.jsx
- src/stock-adjustment-mobile/reducers/program.jsx
- src/stock-adjustment-mobile/reducers/reasons.jsx
- src/stock-adjustment-mobile/reducers/source-destination.jsx
- src/stock-adjustment-mobile/reducers/toasts.jsx
- src/stock-adjustment-mobile/store.jsx
- src/stock-issue-mobile/issue-app.jsx
- src/stock-issue-mobile/issue-mobile.module.js
- src/stock-issue-mobile/issue-mobile.routes.js
- src/stock-issue-mobile/issue-mobile.wrapper.jsx
- src/stock-issue-mobile/reducers/adjustment.jsx
- src/stock-issue-mobile/reducers/facilities.jsx
- src/stock-issue-mobile/reducers/product-options.jsx
- src/stock-issue-mobile/reducers/program.jsx
- src/stock-issue-mobile/reducers/reasons.jsx
- src/stock-issue-mobile/reducers/source-destination.jsx
- src/stock-issue-mobile/reducers/toasts.jsx
- src/stock-issue-mobile/store.jsx
TICKET; https://openlmis.atlassian.net/browse/MW-1159
- add product page for Issue. 
- additional changes in reducers to avoid conflicts with 'Store' while restarting/reloading app.
> MW-1159: AddProductPage for issue - generic approach, fixed reducers

- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-adjustment-mobile/adjustment-app.jsx
- src/stock-adjustment-mobile/adjustment-form.component.jsx
- src/stock-adjustment-mobile/components/block-list.component.jsx
- src/stock-adjustment-mobile/edit-product-page/edit-product-page.jsx
- src/stock-adjustment-mobile/program-select.jsx
- src/stock-issue-mobile/issue-app.jsx
- src/stock-issue-mobile/issue-mobile.wrapper.jsx
- src/stock-receive-mobile/receive-app.jsx
- src/stock-receive-mobile/receive-mobile.routes.js
- src/stock-receive-mobile/receive-mobile.wrapper.jsx
TICKET: https://openlmis.atlassian.net/browse/MW-1164
including tickets: https://openlmis.atlassian.net/browse/MW-1166, https://openlmis.atlassian.net/browse/MW-1167 (it is a generic apporach therefore the changes aren't big).
> MW-1164: AddReceive - including Edit/Submit mode

- src/stock-adjustment-mobile/_adjustment-mobile.scss
- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-adjustment-mobile/adjustment-app.jsx
- src/stock-adjustment-mobile/adjustment-form.component.jsx
- src/stock-adjustment-mobile/components/block-list.component.jsx
- src/stock-adjustment-mobile/edit-product-page/edit-product-page.jsx
- src/stock-adjustment-mobile/program-select.jsx
- src/stock-adjustment-mobile/store.jsx
- src/stock-issue-mobile/issue-app.jsx
- src/stock-issue-mobile/issue-mobile.wrapper.jsx
- src/stock-receive-mobile/messages_en.json
- src/stock-receive-mobile/receive-app.jsx
- src/stock-receive-mobile/receive-mobile.html
- src/stock-receive-mobile/receive-mobile.module.js
- src/stock-receive-mobile/receive-mobile.routes.js
- src/stock-receive-mobile/receive-mobile.wrapper.jsx
- src/stock-receive-mobile/reducers/adjustment.jsx
- src/stock-receive-mobile/reducers/facilities.jsx
- src/stock-receive-mobile/reducers/product-options.jsx
- src/stock-receive-mobile/reducers/program.jsx
- src/stock-receive-mobile/reducers/reasons.jsx
- src/stock-receive-mobile/reducers/source-destination.jsx
- src/stock-receive-mobile/reducers/toasts.jsx
- src/stock-receive-mobile/store.jsx
TICKET: https://openlmis.atlassian.net/browse/MW-1163
PR will be as a draft until PR (MW-1173) will be merged.
> MW-1163: added ProgramSelection for Receive, setup Receive module

- src/stock-adjustment-mobile/_adjustment-mobile.scss
- src/stock-adjustment-mobile/add-products-page/add-product-page.jsx
- src/stock-receive-mobile/add-lot-code.jsx
- src/stock-receive-mobile/receive-app.jsx
- src/stock-receive-mobile/receive-mobile.routes.js
- src/stock-receive-mobile/receive-mobile.wrapper.jsx
TICKET: https://openlmis.atlassian.net/browse/MW-1165
> MW-1165: added 'AddLotCode' page for Receive on mobile app

- CHANGELOG.md
- src/stock-physical-inventory-draft/physical-inventory-draft.controller.js
> OLMIS-7594: Add possibility to use same LotCode for different products

- Jenkinsfile
- npm-shrinkwrap.json
- yarn.lock
This should allow Jenkins to clean up the workspaces for this repo
> Add clean up steps to Jenkinsfile

- CHANGELOG.md
- src/stock-on-hand-mobile/pages/program-select.jsx
- src/stock-on-hand-mobile/reducers/programs.jsx
- src/stock-on-hand-mobile/stock-on-hand-app.jsx
- src/stock-on-hand-mobile/stock-on-hand.wrapper.jsx
- src/stock-on-hand-mobile/store.jsx
[OLMIS-7655]: https://openlmis.atlassian.net/browse/OLMIS-7655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OLMIS-7655: Enable selecting program and facility on mobile stock on hand

- src/stock-on-hand-mobile/pages/program-select.jsx
> OLMIS-7655: Updated program select component

- CHANGELOG.md
- src/stock-on-hand-mobile/_stock-on-hand-mobile.scss
- src/stock-on-hand-mobile/components/stock-on-hand-table-component.jsx
- src/stock-on-hand-mobile/pages/program-select.jsx
- src/stock-on-hand-mobile/pages/stock-on-hand.jsx
- src/stock-on-hand-mobile/stock-on-hand-app.jsx
- src/stock-on-hand-mobile/stock-on-hand.wrapper.jsx
Added table to mobile stock on hand page
I added scss file and I was thinking about previous files added by me which had style defined in react components. Should I add their style in scss in this particular PR?
[OLMIS-7657]: https://openlmis.atlassian.net/browse/OLMIS-7657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OLMIS-7657: Add table to mobile Stock on Hand page

- src/stock-on-hand-mobile/_stock-on-hand-mobile.scss
- src/stock-on-hand-mobile/components/stock-on-hand-table-component.jsx
- src/stock-on-hand-mobile/pages/product-details.jsx
- src/stock-on-hand-mobile/pages/stock-on-hand.jsx
- src/stock-on-hand-mobile/reducers/product.jsx
- src/stock-on-hand-mobile/stock-on-hand-app.jsx
- src/stock-on-hand-mobile/stock-on-hand.routes.js
- src/stock-on-hand-mobile/store.jsx
> OLMIS-7659: Implement product info page

- src/stock-on-hand-mobile/_stock-on-hand-mobile.scss
- src/stock-on-hand-mobile/components/stock-on-hand-table-component.jsx
> OLMIS-7657: Update mobile SOH table

- src/stock-on-hand-mobile/_stock-on-hand-mobile.scss
> OLMIS-7655: Update header with back button

- CHANGELOG.md
- src/stock-adjustment-creation/source-destination.service.js
- src/stock-reason/stock-reason-cache.run.js
- src/stock-reason/stock-reasons.factory.js
- src/stock-valid-destinations/destination-cache.run.js
- src/stock-valid-sources/source-cache.run.js
Ticket:
https://openlmis.atlassian.net/browse/OLMIS-7954
Changes:
Added fixes to improve performance on login page
> OLMIS-7954: Added fixes to improve performance on login page

- CHANGELOG.md
- src/stock-issue-creation/issue-creation.routes.js
Task:
https://openlmis.atlassian.net/browse/OLMIS-7991
Changes:
Filtered out lots that not expired on Issue screeen
> OLMIS-7991: Filtered out lots that not expired on Issue screeen

- src/stock-physical-inventory-draft/_physical-inventory-draft.scss
- src/stock-reasons-modal/_stock-reasons.scss
Updating the styles in order to make olmis support RTL languages
ticket: https://openlmis.atlassian.net/browse/OIS-24
> OIS-24: improved styles that were not supporting RTL

- CHANGELOG.md
- src/stock-add-products-modal/add-products-modal.controller.js
- src/stock-add-products-modal/add-products-modal.html
- src/stock-adjustment-creation/adjustment-creation.controller.js
- src/stock-adjustment-creation/adjustment-creation.html
- src/stock-physical-inventory-draft/physical-inventory-draft.controller.js
- src/stock-physical-inventory-draft/physical-inventory-draft.html
Task:
https://openlmis.atlassian.net/browse/OLMIS-8126
Changes:
Fixed display of expiration date for lots
> OLMIS-8126: Fixed display of expiration date for lots

- CHANGELOG.md
- src/stock-card-summary-list/messages_en.json
- src/stock-card-summary-list/stock-card-summary-list.controller.js
- src/stock-card-summary-list/stock-card-summary-list.controller.spec.js
- src/stock-card-summary-list/stock-card-summary-list.html
- src/stockmanagement/stockmanagement-calculate.service.js
Task:
https://openlmis.atlassian.net/browse/OE-100
Changes:
Added quantity-unit-toggle to Stock on Hand page
> OE-100: Added quantity-unit-toggle to Stock on Hand page
